### ISSUE TITLE
Remove time dependency

### ISSUE THREAD

**Issue by bjornbm** [bjornbm/dimensional#30]
There is a dependency on the time library to for the `toDiffTime` and `fromDiffTime` functions. The functions are trivial enough that the dependency probably isn't justified. I propose removing the dependency.

(We could keep the functions with the same name but relax the types to any `Real`/`Frac` instead of `DiffTime`. The intent would hopefully be clear, but not enforcing it with the type is a bit iffy.)

**Comment by dmcclean** [comment]
Here's a puzzle. master's `build-depends` list doesn't mention the 'time' package. And the SIUnits module doesn't `import Data.Time`. But somehow the `fromDiffTime` and `toDiffTime` functions that mention `Time` compile anyway.

How on earth is that happening?

**Comment by dmcclean** [comment]
Answer:

```haskell
{-# DEPRECATED fromDiffTime, toDiffTime "These will probably go away." #-}
fromDiffTime :: (Real a, Fractional b) => a -> Time b
fromDiffTime = (*~ second) . realToFrac
toDiffTime :: (Real a, Fractional a, Fractional b) => Time a -> b
toDiffTime = realToFrac . (/~ second)
```

The `Time` type mentioned here is the one from the Quantities module. Somehow these types have changed to not mention `DiffTime` at all, possibly by some mislaid global search and replace?

At any rate, since these are presently useless, and deprecated, and we already don't have a dependency on the time module, I am deleting them. The actual functionality will move to dimensional-dk-experimental.

**Comment by dmcclean** [comment]
Wait, rereading the thread, apparently the change was made on purpose. Not going to delete it yet until experimental is in better shape.
